### ISSUE TITLE
No need to compilation

### ISSUE THREAD

**Issue by JoshuaThieriot** [sahwa/ChromoPainterV2#2]
Just want to notify all the users like me that this version does not need compilation.
You can simply git clone and run it :)

**Comment by sahwa** [comment]
Ah - in your case that's right, I pushed a version which contained the binary that I had compiled locally. But it's always best to compile it for your own system, as there's a good chance that it won't work if the architecture and linked libraries are different. Thanks for letting me know, I'll delete the binary and let users compile it themselves to avoid any issues!
